        const dial = document.getElementById("dial");
        const title = dial.querySelector("#title");
        const container = document.getElementById("container");
        const author = dial.querySelector("#author");
        const video = dial.querySelector("#video");
        const dial2 = document.getElementById("dial2");
        const won = document.getElementById("won");
        const greeting = document.getElementById("greeting")
        const goals = dial2.querySelector("#goals")
        const nameID = dial2.querySelector("#name")
        const colourInput = dial2.querySelector("#colour")
        const progress = document.getElementById("Progress")
        const percentage = document.getElementById("percentage")
        let titleList = JSON.parse(localStorage.getItem("title")) || [];
        let authorList = JSON.parse(localStorage.getItem("author")) || [];
        let imageList = JSON.parse(localStorage.getItem("image")) || [];
        let dateList = JSON.parse(localStorage.getItem("date")) || [];
        let goal = localStorage.getItem("goal") || 100
        let name = localStorage.getItem("name") || ""
        let bg = localStorage.getItem("bg") || "rgb(44, 160, 255)"
        let isMonth = 0;
         let tempDate = new Date();
        let stream = false